config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount ActionCable.server => '/channels'

  get '/', to: 'players#show', as: :home

  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#destroy', as: :logout

  get 'about', to: 'about#about', as: :about

  post 'join/:match_id', to: 'players#join_match', as: :join_match
  post 'play/:match_id', to: 'players#play_match', as: :play_match

  get 'play', to: 'games#play', as: :play
  get 'scores', to: 'matches#scores', as: :scores

  resources :players, only: :index

  resources :matches, only: [:create, :new, :destroy, :update] do
    post :join, on: :member
    post :add_bot, on: :member
    post :create_for_many_humans, on: :collection
    resources :games, only: [:create, :update] do
      post :next, on: :member
      post :reset, on: :member
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'matches#index'
end

app/models/player.rb
class Player < ApplicationRecord
  POSITIONS = [0, 1, 2, 3]
  has_many :game_players
  has_many :games, through: :game_players
  has_many :match_players
  has_many :matches, -> { order(created_at: :desc) }, through: :match_players

  before_save do |player|
    if player.name.blank?
      player.name = Names::NAMES.sample
    end
  end

  def human?
    human
  end

  def points
    game_players.map(&:game_points).sum
  end

  def game_count
    games.count
  end
end

app/models/players.rb
class Players

  attr_reader :players

  delegate :[], :each, :map, :select, :reject, :find, :max_by, :first, :each_with_index, to: :players

  def initialize(game)
    @game = game
    @players = game.match.players.order(:position).map do |p|
      GamePlayer.new(p, game)
    end
  end

  def winner
    @players.max_by(&:points)
  end

  def human_player
    @players.find { |p| p.human? }
  end

  def forehand
    @players.find(&:forehand?)
  end

  def next_from(player)
    @players.find do |p|
      p.position == (player.position + 1) % 4
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def join_match
    match = Match.find(params[:match_id])
    MatchPlayer.create(match: match, player: @player)

    if match.match_players.count == 4
      match.deal_game

      redirect_to play_path
    else
      redirect_to home_path
    end
  end
  
  def play_match
    match = Match.find(params[:match_id])
    set_match_cookies(match)

    redirect_to play_path
  end

  def show
    if @player.present?
      @my_matches = @player.matches
      @open_matches = Match.open_matches_for(@player)
    else
      redirect_to login_path unless @player.present?
    end
  end

  def index
    @players = Player.where(human: true)
  end
end

app/views/players/_speech_bubble.erb
<div class="speech-bubble visible" id="js-speech-bubble-<%= player.position%>">
  <%= message %>
</div>

app/views/players/index.html.erb
<div class="container mt-5 mw-70">
  <h2 class="mb-2">Players</h2>
  <table class="table players-table">
    <% @players.each do |player| %>
      <tr>
        <td>
          <span class="player-name">
            <%= player.name %>
          </span>
        </td>

        <td>
          <span class="player-total-points">
            <%= player.game_players.map(&:game_points).sum %>
          </span>
        </td>

        <td>
          <span class="player-hands-played">
            <%= player.games.count %>
          </span>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/players/new.html.erb
<div class="container">
  <h1>Join Game</h1>
  <%= bootstrap_form_for([@match, @player]) do |f| %>
    <%= f.text_field :name, label: "Name", class: "form-control", placeholder: "name" %>
    <%= f.submit "join game", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/players/show.html.erb
<div class="container mb-5 mt-3">
  <div class="d-flex justify-content-between align-items-center">
    <h2 class="mb-4"><%= @player.name %></h2>
    <%= link_to 'logout', logout_path, method: :post, class: 'btn btn-secondary' %>
  </div>

  <div class="player-total-points">
    Scored <%= @player.game_players.map(&:game_points).sum %> points in total
  </div>

  <div class="player-hands-played">
    Played <%= @player.games.count %> hands
  </div>

  <hr>
  <%= link_to 'New Game', create_for_many_humans_matches_path(), method: :post, class: 'btn btn-primary', title: 'new single player game' %>
  <hr>

  <h2 class="mb-4">My games</h2>
  <% if @my_matches.empty? %>
    <div class='no-matches-text'>You have not joined any games</div>
  <% end %>
  <div class='match-cards-container'>
    <% @my_matches.each do |match| %>
      <div class='match-card-container'>
        <%= render 'matches/match_listing', match: match, joined: true %>
      </div>
    <% end %>
  </div>

  <hr>

  <h2 class="mb-4">Open games</h2>
  <% if @open_matches.empty? %>
    <div class='no-matches-text'>The are no games available to join</div>
  <% end %>
  <div class='match-cards-container'>
    <% @open_matches.each do |match| %>
      <div class='match-card-container'>
        <%= render 'matches/match_listing', match: match, joined: false %>
      </div>
    <% end %>
  </div>

  <hr>

  <h2 class="mb-4">New game</h2>

  <%= link_to '', matches_path(match: { human_count: 1 }), method: :post, class: 'btn btn-primary new-game-button humans-1', title: 'new single player game' %>
  <%= link_to '', matches_path(match: { human_count: 2 }), method: :post, class: 'btn btn-primary new-game-button humans-2', title: 'new game with 2 humans, 2 bots' %>
  <%= link_to '', matches_path(match: { human_count: 3 }), method: :post, class: 'btn btn-primary new-game-button humans-3', title: 'new game with 3 humans, 1 bot' %>
  <%= link_to '', matches_path(match: { human_count: 4 }), method: :post, class: 'btn btn-primary new-game-button humans-4', title: 'new game with 4 humans' %>
</div>