config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount ActionCable.server => '/channels'

  get '/', to: 'players#show', as: :home

  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#destroy', as: :logout

  get 'about', to: 'about#about', as: :about

  post 'join/:match_id', to: 'players#join_match', as: :join_match
  post 'play/:match_id', to: 'players#play_match', as: :play_match

  get 'play', to: 'games#play', as: :play
  get 'scores', to: 'matches#scores', as: :scores

  resources :players, only: :index

  resources :matches, only: [:create, :new, :destroy, :update] do
    post :join, on: :member
    post :add_bot, on: :member
    post :create_for_many_humans, on: :collection
    resources :games, only: [:create, :update] do
      post :next, on: :member
      post :reset, on: :member
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'matches#index'
end

app/models/match.rb
class Match < ApplicationRecord
  has_many :games, -> { order(:id) }, dependent: :destroy
  has_many :match_players, -> { order(:id) }
  has_many :players, through: :match_players

  attribute :human_name, :text
  attribute :human_count, :integer

  accepts_nested_attributes_for :players

  def self.open_matches_for(player)
    open_matches.reject { |m| m.players.include?(player) }
  end

  def self.open_matches
    all.order(created_at: :desc).filter do |match|
      match.players.count < 8
    end
  end

  def deal_game
    game = Game.deal_game(id, next_game_players)
    Runner.new(game).advance!
    game
  end

  def earlier_games(game_id)
    games.where('id < ?', game_id)
  end

  def stage
    return 'waiting' if players.count < 4

    return 'in progress'
  end

  def points_for(player)
    games.map(&:game_players).flatten.filter do |gp|
      gp.player_id == player.id
    end.map(&:game_points).sum
  end


  def next_game_players
    player_count = match_players.size
    last_forehand_player_id = games.last&.forehand&.player_id
    last_forehand_position = match_players.find_by(player_id: last_forehand_player_id)&.position || -1
    forehand_position = (last_forehand_position + 1) % (player_count)
    players = get_relative_player_positions(player_count).map do |rel_pos|
      pos = (rel_pos + forehand_position) % player_count
      match_players.find_by(position: pos)
    end

    players
  end

  private

  def get_relative_player_positions(player_count)
    case player_count
    when 4, 5
      return [0, 1, 2, 3]
    when 6
      return [0, 2, 3, 4]
    else
      return [0, 2, 4, 5]
    end
  end
end

app/controllers/api/matches_controller.rb
class Api::MatchesController < ApplicationController
  def create
    match = Match.create
    match.match_players.create(match: match, player: @player)
    bot_count = 4 - match_params[:human_count].to_i

    bot_count.times do
      bot = Player.create(human: false)
      match.match_players.create(match: match, player: bot)
    end

    if match.match_players.count == 4
      game = match.deal_game

      set_game_cookie(game)
    end
    set_match_cookie(match)

    render_match(match)
  end

  def current
    render_match
  end

  def list_open

    if !@player
      render(
        json: [],
        each_serializer: MatchSerializer,
        root: 'data'
      )
    else
      render(
        json: Match.open_matches_for(@player),
        each_serializer: MatchSerializer,
        root: 'data'
        # only: [:id],
        # methods: [:hand_description, :days_old],
        # include: {
        #   players: {
        #     only: [:id, :name, :human]
        #   }
        # },
        # player: @player
      )
    end
  end

  def set
    match = Match.find(match_params[:id])
    set_match_cookie(match)

    render(
      json: match,
      root: 'data',
      serializer: MatchSerializer
    )
  end

  def goto_last_game
    match = Match.find(match_params[:id])
    set_match_cookie(match)
    game = match.games.reject(&:finished?).last || match.deal_game
    set_game_cookie(game)
    render(
      json: game,
      serializer: GameSerializer,
      root: 'data'
      # include: {
      #   players: {
      #     only: [:id, :name, :human]
      #   }
      # }
    )
  end

  private

  def match_params
    params.permit(:id, :human_count)
  end

  def render_match(match = @match)
    render(
      json: match,
      serializer: MatchSerializer,
      root: 'data'
    )
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def new
    @match = Match.new
    @human_count_select = human_count_select
  end

  def destroy
    Match.find(params[:id]).destroy!
    redirect_to matches_path
  end

  def create_for_many_humans
    @match = Match.create
    @match.match_players.create(player: @player)

    play_if_full
  end

  def join
    @match = Match.find(params[:id])
    @match.match_players.create(player: @player)

    play_if_full
  end

  def add_bot
    @match = Match.find(params[:id])
    bot = Player.create(human: false)
    @match.match_players.create(player: bot)

    play_if_full
  end

  def create
    match = Match.create
    match.match_players.create(match: match, player: @player)
    bot_count = 4 - match_params[:human_count].to_i

    bot_count.times do
      bot = Player.create(human: false)
      match.match_players.create(match: match, player: bot)
    end

    if match.match_players.count == 4
      match.deal_game

      set_match_cookies(match)

      redirect_to play_path
    else
      redirect_to home_path
    end
  end

  def scores
    if @match.present?
      render locals: MatchPointsPresenter.new(@match).props
    else
      redirect_to home_path
    end
  end

  private

  def play_if_full
    @match.reload
    if @match.match_players.count == 4
      @match.deal_game

      set_match_cookies(@match)

      redirect_to play_path
    else
      redirect_to home_path
    end
  end


  def human_count_select
    [
      ["single player", 1],
      ["1 friend, 2 bots", 2],
      ["2 friends, 1 bot", 3],
      ["3 friends", 4]
    ]
  end

  def match_params
    params.require(:match).permit(:human_name, :human_count)
  end
end

app/helpers/match_helper.rb
module MatchHelper
  def hand_count_text(match)
    if match.games.count == 0
      'not started'
    else
      "hand #{match.games.count}"
    end
  end

  def match_days_ago_text(match)
    days = match_days_ago(match)
    days == 0 ? 'today' : "#{days} days ago"
  end

  def player_names_text(match)
    match.players.map(&:name).join(', ')
  end

  private

  def round_description
  end

  def match_days_ago(match)
    (Time.zone.now - match.created_at).to_i / 1.day
  end
end

app/views/matches/_match_listing.html.erb
<div class="card match-card">
  <div class="card-body">
    <p class="card-text">
      <div class="player-points">
        <%= "#{match.points_for(@player)}" %>
      </div>
      <div class="hand-count">
        <%= hand_count_text(match) %>
      </div>
      <div class="match-days-ago">
        <%= "Started #{match_days_ago_text(match)}" %>
      </div>
    </p>
    <p class="card-text">
      <%= render 'matches/match_listing/player_names', players: match.players %>
    </p>
  </div>
  <div class="card-footer">
    <% if joined %>
      <% if match.players.count < 4 %>
        <p class="card-text">Waiting for players</p>
        <%= link_to "Add bot", add_bot_match_path(match), method: :post %>
      <% else %>
        <%= link_to "Go to game", play_match_path(match), method: :post, class: 'stretched-link' %>
      <% end %>
    <% else %>
        <%= link_to "Join game", join_match_path(match), method: :post, class: 'stretched-link' %>
    <% end %>
  </div>
</div>

app/views/matches/_player.html.erb
<% if link %>
  <%= link_to player.name, link %>
<% else %>
  <%= player.name %>
<% end %>

app/views/matches/_points.html.erb
<div class="points-container center-container <%= visible ? '' : 'd-none' %>" id="js-points-container">
  <div class="points-container-grid">
    <% @players.each do |p| %>
      <div class="d-flex justify-content-center">
        <%= p.name %>
      </div>
    <% end %>
    <div class=""></div>
    <div style="display: contents" id="js-points">
      <% @match.games.select(&:finished?).map(&:summary).each do |summary| %>
        <% summary[:players].each do |player| %>
          <div class="d-flex justify-content-center game-point <%= points_classes(player) %>" >
            <div class="game-point-inner">
              <%= player[:points] %>
            </div>
          </div>
        <% end %>
        <div class="game-shorthands">
          <span class="bid-shorthand <%= bid_classes(summary[:bid]) %>">
            <%= summary[:bid][:shorthand] %>
          </span>
          <% summary[:announcements].each do |a| %>
            <span class="<%= announcement_classes(a) %>">
              <%= a[:shorthand] %>
            </span>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/matches/new.html.erb
<div class="container">
  <h1>Start a new game for <%= @player.name %></h1>
  <%= bootstrap_form_for(@match) do |f| %>
    <%= f.select :human_count, @human_count_select, label: "Game setup" %>
    <%= f.submit "create game", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/matches/scores.html.erb
<div class="container mt-5" id="js-points">
  <div class="points-container-grid" style="grid-template-columns: repeat(<%= player_names.size + 1 %>, minmax(1rem, 1fr))">
    <% player_names.each do |name| %>
      <div class="d-flex justify-content-center">
        <%= name %>
      </div>
    <% end %>
    <% if games.empty? %>
      <div class="d-flex justify-content-center no-hands-played">
        No hands played yet!
      </div>
    <% end %>
    <div class=""></div>
    <div style="display: contents" id="js-points">
      <% games.each do |game| %>
        <%= render 'matches/scores/game_points', game %>
      <% end %>
    </div>
  </div>
</div>